server:
  port: 7002
spring:
  application:
    name: shop
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://register-0.register.default.svc.cluster.local:7001/eureka/
    fetch-registry: true
    register-with-eureka: true
feign-client:
  platform-url: http://192.168.10.10:32160