server:
  port: 7003
spring:
  profiles:
    active: feign
  application:
    name: platform
platform:
  clickhouse:
    host: 192.168.10.10
    port: 31678
    database: platform
    user: default
    timeZone: Asia/Shanghai